# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZemogaMobileTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZemogaMobileTest
  pod 'NotificationBannerSwift', '~> 3.0.0'
  pod 'Alamofire', '~> 5.5'
  pod 'RealmSwift'

  target 'ZemogaMobileTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZemogaMobileTestUITests' do
    # Pods for testing
  end

end
